name: absensi_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cloud_firestore: 3.4.3
  convex_bottom_bar: 3.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: 3.6.2
  firebase_core: 1.20.0
  firebase_storage: 10.3.4
  geocoding: 2.0.4
  geolocator: 9.0.1
  get: 4.6.5
  google_fonts: ^3.0.1
  image_picker: 0.8.5+3
  intl: ^0.17.0
  syncfusion_flutter_datepicker: 20.2.44
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

