// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs1g9BfAOmFZOgQP92rgMKDgDez0Ujwhk',
    appId: '1:545414768867:android:229208e07e2fc030fbfdd6',
    messagingSenderId: '545414768867',
    projectId: 'absen-online-app-a3bb8',
    storageBucket: 'absen-online-app-a3bb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ZKfsU87FAoHnI86dUlA8RfBL1Qihxfo',
    appId: '1:545414768867:ios:3e8a497ba5a7d060fbfdd6',
    messagingSenderId: '545414768867',
    projectId: 'absen-online-app-a3bb8',
    storageBucket: 'absen-online-app-a3bb8.appspot.com',
    androidClientId: '545414768867-ag1vpo4nhla3faiep41427v83q2nqc05.apps.googleusercontent.com',
    iosClientId: '545414768867-5ak5go6amupip079get728patu31gfbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensiApp',
  );
}
